version: '3'
services:
  runner-image-runtime:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9001:8000
    environment:
      - DB_NAME=test-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=runner-image-db
      - DB_PORT=5432
    depends_on:
      - runner-image-db
    volumes:
      - .:/app
  runner-image-db:
    image: postgres:14.1-alpine
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./pgsql:/var/lib/postgresql/data
