lang = "Python"
package_type = "executable"

[[links]]
icon = "FaLink"
internal = true
label = "Open Test Studio"
link = "https://db-compose-runtime-test-env-675766508318.asia-south1.run.app"

[[links]]
icon = "FaCodeBranch"
internal = true
label = "Pull Requests"
link = "https://github.com/ginger-society/ginger-db-compose-runtime/pulls"

[[links]]
icon = "FaRegPlayCircle"
internal = true
label = "Pipelines"
link = "https://github.com/ginger-society/ginger-db-compose-runtime/actions"

[[links]]
icon = "FaGithub"
internal = true
label = "Browse Repo"
link = "https://github.com/ginger-society/ginger-db-compose-runtime"
