[version]
channel = "Nightly"
major = 0
minor = 10
patch = 0
revision = 0

[[references]]
file_name = "server/settings.py"
output_type = "String"
variable = "VERSION"

[[references]]
file_name = "pyproject.toml"
output_type = "String"
variable = "version"

[settings]
git_url_prefix = "https://github.com/ginger-society/ginger-db-compose-runtime"
