lang = "Python"
organization_id = "ginger-society"
service_type = "RPCEndpoint"
spec_url = "/swagger/?format=openapi"

[urls]
dev = "http://localhost:9002"
stage = "http://localhost:9002"

[services]
