lang = "Python"
organization_id = "ginger-society"
dir = "."
refs_file = "src/references.py"
spec_url = "/swagger/?format=openapi"
service_type = "RPCEndpoint"

[services."@ginger-society/IAMService"]
prod_k8 = "http://iam-service-api-service/iam"
stage = "https://api-staging.gingersociety.org/iam"
stage_k8 = "http://iam-service-api-service/iam"
dev = "http://localhost:8080/iam"
prod = "https://api.gingersociety.org/iam"

[portals_refs."@ginger-society/iam-frontend-users"]
dev = "http://localhost:3001"
stage = "https://iam-staging.gingersociety.org"
prod = "https://iam.gingersociety.org"

[ws_refs."@ginger-society/IAMService"]
prod_k8 = ""
dev = ""
stage_k8 = ""
prod = ""
stage = ""

[urls]
dev = "http://localhost:3013"
stage = "https://db-compose-runtime-test-env-675766508318.asia-south1.run.app"
prod = "https://iam-db.gingersociety.org"

[urls_ws]
