# Generated by Ginger 5.3.4 on 2024-07-13 08:23

import ginger.db.models.deletion
from ginger.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='app',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'app',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_hash', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(blank=True, max_length=400, null=True)),
                ('app', models.ForeignKey(on_delete=ginger.db.models.deletion.CASCADE, to='src.app')),
                ('user', models.ForeignKey(on_delete=ginger.db.models.deletion.CASCADE, related_name='tokens', to='src.user')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('users', models.ManyToManyField(related_name='groups', to='src.user')),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
