# Generated by GingerDJ 5.7 on 2024-10-28 12:03

from gingerdj.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_group_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='field_one',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
