apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dry-run
  namespace: tasks-ginger-db-compose-runtime
  annotations:
    x-ginger-task-namespace: "ginger-db-compose-runtime"  # Custom annotation
    x-ginger-task-trigger-branch: '["refs/heads/main"]'  # Allowed branches

spec:
  workspaces:
      - name: source
      - name: ssh-credentials  # Store SSH keys
      - name: ssh-config  # Store SSH setup
      - name: kubeconfig
      - name: buildah-cache  # Workspace for caching
      - name: pipeline-secrets
      - name: general-purpose-cache
  steps:

    - name: dry-run
      image: containers.gingersociety.org/gingersociety/ginger-db-compose-runtime:prod
      script: |
        #!/bin/sh
        set -e  # Exit on error

        cd /app

        python manage.py makemigrations --verbosity 3

      securityContext:
        privileged: true

        
      


