name: Build, Push Docker Image for runner and migrator

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Report failure if checkout fails
      if: failure()
      run: ginger-connector update-pipeline stage failed

    - name: Install ginger-apps
      run: bash -c "$(curl -fsSL https://raw.githubusercontent.com/ginger-society/infra-as-code-repo/main/rust-helpers/install-pipeline-clis.sh)"
    - name: Report failure if ginger-apps installation fails
      if: failure()
      run: ginger-connector update-pipeline stage failed

    - name: Authenticate with ginger-auth
      id: ginger-auth
      run: ginger-auth token-login ${{ secrets.GINGER_TOKEN }}
    - name: Report failure if authentication fails
      if: failure()
      run: ginger-connector update-pipeline stage failed

    - name: Update status to running
      run: ginger-connector update-pipeline stage running

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
    - name: Report failure if Docker Hub login fails
      if: failure()
      run: ginger-connector update-pipeline stage failed

    # 🚀 Build and push stage image
    - name: Build Docker image for runtime (stage)
      run: |
        docker buildx build -t ${{ secrets.DOCKER_HUB_USERNAME }}/db-compose-runtime:latest . \
          --build-arg GINGER_TOKEN=${{ secrets.GINGER_TOKEN }} \
          --build-arg GINGER_ENV=stage
    - name: Push Docker image for runtime (stage)
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/db-compose-runtime:latest

    # 🚀 Build and push prod image
    - name: Build Docker image for runtime (prod)
      run: |
        docker buildx build -t ${{ secrets.DOCKER_HUB_USERNAME }}/db-compose-runtime-prod:latest . \
          --build-arg GINGER_TOKEN=${{ secrets.GINGER_TOKEN }} \
          --build-arg GINGER_ENV=prod
    - name: Push Docker image for runtime (prod)
      run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/db-compose-runtime-prod:latest

    - name: Report failure if runtime Docker push fails
      if: failure()
      run: ginger-connector update-pipeline stage failed

    # TODO: update a running instance and publish
    # - name: Publish stage using ginger-connector
    #   run: ginger-connector publish stage

    - name: Update status to passing
      if: success()
      run: ginger-connector update-pipeline stage passing

    - name: Trigger dependent pipelines
      if: success()
      run: ginger-connector trigger-dependent-pipelines ${{ secrets.GH_TOKEN }}
